CC=clang
CXX=clang++
CXXFLAGS=-std=c++11
RM=rm -f
CPPFLAGS=-g
TARGETS=function functionprototype passbyvalue passbypointer passarray passarraypointer templatefunction

all: $(TARGETS)

clean:
	$(RM) $(TARGETS)
