CC=clang
CXX=clang++
CXXFLAGS=-std=c++11
RM=rm -f
CPPFLAGS=-g
TARGETS=loops factorial comma range while arrays arraytemplate vectors vectorsMemOnly vectorsMore

all: $(TARGETS)

clean:
	$(RM) $(TARGETS)
